### ISSUE TITLE
您好，能给出requirements.txt么？谢谢！

### ISSUE THREAD

**Issue by xiaoxiong74** [GaoQ1/rasa_chatbot_cn#12]

**Comment by GaoQ1** [comment]
已加

**Comment by xiaoxiong74** [comment]
跑demo测试的时候一直报这个错误，好像是kereas版本问题，但如何更新tensorflow中的keras版本呢？
   @@@tensorflow版本是1.10.0(内置keras=2.16)，请问大佬有遇到过类似问题么？谢谢！

(rasa) [root@hsza rasa_chatbot_cn]# python -m rasa_core.run --nlu models/nlu/default/current --core models/dialogue_keras --endpoints endpoints.yml
2019-02-19 11:26:09 INFO     root  - Rasa process starting
"not found" "san silvestro"
"not found" "notte di san silvestro"
2019-02-19 11:26:23.892670: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
INFO:tensorflow:Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
2019-02-19 11:26:23 INFO     tensorflow  - Restoring parameters from models/nlu/default/current/intent_classifier_tensorflow_embedding.ckpt
2019-02-19 11:26:24 WARNING  py.warnings  - /root/anaconda3/envs/rasa/lib/python3.6/site-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Traceback (most recent call last):
  File "/root/anaconda3/envs/rasa/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/rasa/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/run.py", line 254, in <module>
    endpoints=_endpoints)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/run.py", line 227, in load_agent
    action_endpoint=endpoints.action)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/agent.py", line 275, in load
    ensemble = PolicyEnsemble.load(path) if path else None
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 188, in load
    policy = policy_cls.load(policy_path)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa_core/policies/keras_policy.py", line 261, in load
    model = load_model(model_file)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 229, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 306, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 173, in deserialize_keras_object
    list(custom_objects.items())))
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 293, in from_config
    layer = layer_module.deserialize(conf, custom_objects=custom_objects)
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/layers/serialization.py", line 64, in deserialize
    printable_module_name='layer')
  File "/root/anaconda3/envs/rasa/lib/python3.6/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 193, in deserialize_keras_object
    function_name)
ValueError: Unknown layer:name
