### ISSUE TITLE
ModuleNotFoundError: No module named 'bert_serving'

### ISSUE THREAD

**Issue by loveJasmine** [GaoQ1/rasa_chatbot_cn#18]
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/rasa_chatbot_cn$ python bot.py train-nlu-gao
Using TensorFlow backend.
2019-03-11 15:01:16 INFO     rasa_nlu_gao.training_data.loading  - Training data format of data/rasa_dataset_training.json is rasa_nlu
2019-03-11 15:01:16 INFO     rasa_nlu_gao.training_data.training_data  - Training data stats: 
	- intent examples: 1019 (13 distinct intents)
	- Found intents: 'inform_package', 'deny', 'goodbye', 'inform_item', 'request_search', 'unknown_intent', 'inform_other_phone', 'greet', 'request_management', 'confirm', 'thanks', 'inform_time', 'inform_current_phone'
	- entity examples: 883 (6 distinct entities)
	- found entities: 'time', 'price', 'package', 'phone_number', 'data_plan', 'item'

Traceback (most recent call last):
  File "bot.py", line 136, in <module>
    train_nlu_gao()
  File "bot.py", line 112, in train_nlu_gao
    trainer = Trainer(config.load("configs/config_embedding_bilstm.yml"))
  File "/home/ub16c9/ub16_prj/rasa_chatbot_cn/.venv/lib/python3.6/site-packages/rasa_nlu_gao/model.py", line 152, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/ub16c9/ub16_prj/rasa_chatbot_cn/.venv/lib/python3.6/site-packages/rasa_nlu_gao/components.py", line 49, in validate_requirements
    from rasa_nlu_gao import registry
  File "/home/ub16c9/ub16_prj/rasa_chatbot_cn/.venv/lib/python3.6/site-packages/rasa_nlu_gao/registry.py", line 38, in <module>
    from rasa_nlu_gao.featurizers.bert_vectors_featurizer import BertVectorsFeaturizer  # customize
  File "/home/ub16c9/ub16_prj/rasa_chatbot_cn/.venv/lib/python3.6/site-packages/rasa_nlu_gao/featurizers/bert_vectors_featurizer.py", line 16, in <module>
    from bert_serving.client import BertClient
ModuleNotFoundError: No module named 'bert_serving'
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/rasa_chatbot_cn$ 
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/rasa_chatbot_cn$ 
(.venv) ub16c9@ub16c9-gpu:~/ub16_prj/rasa_chatbot_cn$

**Comment by GaoQ1** [comment]
这个你可以看下[rasa对话系统踩坑记（八）](https://www.jianshu.com/p/6a93209c48a4)
