### ISSUE TITLE
Exception: Not all required packages are installed. Please install duckling

### ISSUE THREAD

**Issue by Growing-bison** [GaoQ1/rasa_chatbot_cn#20]
When i run “python bot.py train-nlu”, it occured as follows:

`
Using Theano backend.
2019-03-14 15:27:13 INFO     rasa_nlu.training_data.loading  - Training data format of data/rasa_dataset_training.json is rasa_nlu
2019-03-14 15:27:13 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 1019 (13 distinct intents)
	- Found intents: 'confirm', 'inform_time', 'deny', 'request_search', 'inform_current_phone', 'goodbye', 'thanks', 'inform_package', 'unknown_intent', 'request_management', 'greet', 'inform_other_phone', 'inform_item'
	- entity examples: 883 (6 distinct entities)
	- found entities: 'time', 'phone_number', 'price', 'package', 'item', 'data_plan'

Traceback (most recent call last):
  File "bot.py", line 134, in <module>
    train_nlu()
  File "bot.py", line 98, in train_nlu
    trainer = Trainer(config.load("configs/nlu_embedding_config.yml"))
  File "/home/my/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu/model.py", line 152, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/my/miniconda3/envs/rasa_nlu_gao/lib/python3.6/site-packages/rasa_nlu/components.py", line 63, in validate_requirements
    "Please install {}".format(", ".join(failed_imports)))
Exception: Not all required packages are installed. To use this pipeline, you need to install the missing dependencies. Please install duckling
`
my environments:
python==3.6.8
tensorflow==1.9.0
theano==1.0.4
rasa-nlu==0.13.2
rasa-nlu-gao==0.2.1

**Comment by GaoQ1** [comment]
很明显，他说了你需要`pip install duckling`

**Comment by Growing-bison** [comment]
忘了说，我是在ubuntu的conda创建虚拟环境当中，对应虚拟环境中conda list列出的packages已经装有ducking。周一去我重新建个python环境之后再运行试下。

**Comment by GaoQ1** [comment]
这个issue我close了
