### ISSUE TITLE
Unable to initialize persistor

### ISSUE THREAD

**Issue by NexusLee** [GaoQ1/rasa_chatbot_cn#25]
rasa-nlu == 0.13.4
rasa-nlu-gao == 0.2.0
rasa-core == 0.12.3
rasa-core-sdk == 0.12.1

python bot.py train-nlu-gao
python -m rasa_nlu_gao.server -c configs/config_embedding_bilstm.yml --path models/nlu_gao/

然后用 postman 请求 localhost:5000/parse?query=xxx 报错

2019-04-01 06:04:18+0000 [-] Log opened.
2019-04-01 06:04:18+0000 [-] Site starting on 5000
2019-04-01 06:04:18+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f7784e01160>
2019-04-01 06:04:24+0000 [-] 2019-04-01 06:04:24 WARNING  rasa_nlu_gao.project  - Using default interpreter, couldn't fetch model: Unable to initialize persistor
2019-04-01 06:04:24+0000 [-] 2019-04-01 06:04:24 ERROR    __main__  - Unable to initialize persistor
2019-04-01 06:04:24+0000 [-] Traceback (most recent call last):
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu_gao/server.py", line 238, in parse
2019-04-01 06:04:24+0000 [-]     self.data_router.parse, data))
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2019-04-01 06:04:24+0000 [-]     result = inContext.theWork()
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2019-04-01 06:04:24+0000 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2019-04-01 06:04:24+0000 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2019-04-01 06:04:24+0000 [-]     return func(*args,**kw)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu_gao/data_router.py", line 249, in parse
2019-04-01 06:04:24+0000 [-]     model)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu_gao/project.py", line 119, in parse
2019-04-01 06:04:24+0000 [-]     interpreter = self._interpreter_for_model(model_name)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu_gao/project.py", line 197, in _interpreter_for_model
2019-04-01 06:04:24+0000 [-]     metadata = self._read_model_metadata(model_name)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu_gao/project.py", line 212, in _read_model_metadata
2019-04-01 06:04:24+0000 [-]     self._load_model_from_cloud(model_name, path)
2019-04-01 06:04:24+0000 [-]   File "/usr/local/lib/python3.6/site-packages/rasa_nlu_gao/project.py", line 251, in _load_model_from_cloud
2019-04-01 06:04:24+0000 [-]     raise RuntimeError("Unable to initialize persistor")
2019-04-01 06:04:24+0000 [-] RuntimeError: Unable to initialize persistor
2019-04-01 06:04:24+0000 [-] "172.17.0.1" - - [01/Apr/2019:06:04:23 +0000] "GET /parse?query=%E6%88%91%E8%A6%81%E6%9F%A5%E6%98%A8%E5%A4%A9%E4%B8%8B%E5%8D%88%E7%9A%84%E6%B5%81%E9%87%8F HTTP/1.1" 500 47 "-" "PostmanRuntime/7.6.0"

**Comment by NexusLee** [comment]
还有个警告 不知道有没有关系

2019-04-01 07:23:44 WARNING  py.warnings  - /usr/local/lib/python3.6/site-packages/rasa_nlu_gao/utils/__init__.py:236: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(read_file(filename, "utf-8"))

**Comment by NexusLee** [comment]
参数还得带 model: current
