### ISSUE TITLE
测试nlu服务时，向127.0.0.1发送post请求返回了页面的html元素

### ISSUE THREAD

**Issue by cabbageNoob** [GaoQ1/rasa_chatbot_cn#34]
nlu服务已成功启动，且5000端口已有信息显示，但我向localhost发送curl -XPOST 127.0.0.1:5000/parse -d"{"q":"帮我查一下上个月流量"}"  请求时，返回了页面html元素

- 下面是返回的一部分页面元素信息：

<div class="snippet">
        <div class="snippetLine">
          <span class="lineno">221</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;request_params = simplejson.loads(</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">222</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;request.content.read().decode('u
tf-8', 'strict'))</code>
        </div><div class="snippetLine">
          <span class="lineno">223</span>
          <code class="code"> &#160; &#160; &#160; &#160;print(request_params)</code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>builtins.UnicodeDecodeError</span>: <span>'utf-8' codec can't decode byte 0xb0 in position 3: invalid start byte</span>
  </div>
</div>

</body></html>

- 这里是出错信息：

2019-05-24 10:35:27+0800 [-] Unhandled Error
        Traceback (most recent call last):
          File "D:\Users\cjh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu_gao\server.py", line 135, in decorat
ed
            return f(*args, **kwargs)
          File "D:\Users\cjh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu_gao\server.py", line 118, in decorat
ed
            return f(*args, **kwargs)
          File "D:\Users\cjh\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\defer.py", line 1613, in unw
indGenerator
            return _cancellableInlineCallbacks(gen)
          File "D:\Users\cjh\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\defer.py", line 1529, in _ca
ncellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "D:\Users\cjh\AppData\Local\Programs\Python\Python36\lib\site-packages\twisted\internet\defer.py", line 1418, in _in
lineCallbacks
            result = g.send(result)
          File "D:\Users\cjh\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_nlu_gao\server.py", line 222, in parse
            request.content.read().decode('utf-8', 'strict'))
        builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 3: invalid start byte

2019-05-24 10:35:27+0800 [-] "127.0.0.1" - - [24/May/2019:02:35:26 +0000] "POST /parse HTTP/1.1" 500 3202 "-" "curl/7.55.1"

求问，是我curl发送的post请求有问题吗？已被此问题纠结很久了，求大佬帮忙看看，十分感谢

**Comment by cabbageNoob** [comment]
这是返回的一部分html页面元素数据
D:\RasaProject\rasa_chatbot_cn>curl -XPOST 127.0.0.1:5000/parse -d"{"q":"帮我查一下上个月流量"}"
<html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last)
:</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

**Comment by GaoQ1** [comment]
请拉取最新的代码尝试下，还有你可以使用postman进去测试。
