### ISSUE TITLE
安装的时候碰到如下错误

### ISSUE THREAD

**Issue by l2009312042** [GaoQ1/rasa_chatbot_cn#39]
ERROR: rasa-nlu 0.15.1 has requirement matplotlib~=2.2, but you'll have matplotlib 3.1.0 which is incompatible.
ERROR: rasa-nlu 0.15.1 has requirement packaging~=18.0, but you'll have packaging 19.0 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement fakeredis~=0.10.0, but you'll have fakeredis 1.0.3 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement fbmessenger~=5.0, but you'll have fbmessenger 6.0.0 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement packaging~=18.0, but you'll have packaging 19.0 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement pika~=0.12.0, but you'll have pika 1.0.1 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement python-socketio~=3.0, but you'll have python-socketio 4.1.0 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement pytz~=2018.9, but you'll have pytz 2019.1 which is incompatible.
ERROR: rasa-core 0.14.5 has requirement redis~=2.0, but you'll have redis 3.2.1 which is incompatible.
ERROR: rasa-core-sdk 0.14.0 has requirement ConfigArgParse~=0.13.0, but you'll have configargparse 0.14.0 which is incompatible.
ERROR: fakeredis 1.0.3 has requirement six>=1.12, but you'll have six 1.11.0 which is incompatible.
Installing collected packages: greenlet, gevent, rasa-sdk, redis, fakeredis, python-socketio, async-generator, fbmessenger, async-timeout, typing-extensions, idna-ssl, yarl, aiohttp, python-dateutil, matplotlib, sanic-jwt, packaging, rasa, rasa-nlu-gao
  Found existing installation: greenlet 0.4.13
ERROR: Cannot uninstall 'greenlet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by l2009312042** [comment]
我刚安装过rasa-core 是可以单独运行的 然后安装的这个工程 报了这么多错误  版本的依赖关系这么严重吗？

**Comment by GaoQ1** [comment]
你怎么安装的？直接`pip install -r requirements.txt`就行了。你创建个虚拟python环境安装吧。你这些错误都是以前依赖间相互冲突的错误。

**Comment by l2009312042** [comment]
我创建了一个虚拟环境后  运行run 报这个错误 
 File "d:\programdata\anaconda3\envs\rasa1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 936, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'policy'

During handling of the above exception, another exception occurred:

**Comment by GaoQ1** [comment]
你看下我README最后，Q&A，可能是那个问题

**Comment by l2009312042** [comment]
@GaoQ1  需要添加哪些路径到PYTHONPATH这个变量下呢？

**Comment by l2009312042** [comment]
在运行trian NLU的时候 又遇到如下错误了 ，还望指点一二，多谢
Training NLU model...
Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 206, in arg_wrapper
    return func(self, *args, **kwargs)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 232, in server_status
    return jsonapi.loads(self._recv(req_id).content[1])
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 164, in _recv
    raise e
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 153, in _recv
    response = self.receiver.recv_multipart()
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\zmq\sugar\socket.py", line 470, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq\backend\cython\socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
  File "zmq\backend\cython\socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
  File "zmq\backend\cython\socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq\backend\cython\socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq\backend\cython\checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\programdata\anaconda3\envs\rasa1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programdata\anaconda3\envs\rasa1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\envs\rasa1\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\cli\train.py", line 84, in train
    kwargs=extract_additional_arguments(args),
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\train.py", line 40, in train
    kwargs=kwargs,
  File "d:\programdata\anaconda3\envs\rasa1\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\train.py", line 135, in train_async
    kwargs=kwargs,
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\train.py", line 188, in _do_training
    fixed_model_name=fixed_model_name,
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\train.py", line 382, in _train_nlu_with_validated_data
    config, nlu_data_directory, _train_path, fixed_model_name="nlu"
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\nlu\train.py", line 81, in train
    trainer = Trainer(nlu_config, component_builder)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\nlu\model.py", line 151, in __init__
    self.pipeline = self._build_pipeline(cfg, component_builder)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\nlu\model.py", line 163, in _build_pipeline
    component = component_builder.create_component(component_cfg, cfg)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\nlu\components.py", line 459, in create_component
    component = registry.create_component_by_config(component_config, cfg)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\nlu\registry.py", line 196, in create_component_by_config
    return component_class.create(component_config, config)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa\nlu\components.py", line 244, in create
    return cls(component_config)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\rasa_nlu_gao\featurizers\bert_vectors_featurizer.py", line 61, in __init__
    identity=identity
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 451, in __init__
    self.available_bc = [BertClient(**kwargs) for _ in range(max_concurrency)]
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 451, in <listcomp>
    self.available_bc = [BertClient(**kwargs) for _ in range(max_concurrency)]
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 108, in __init__
    s_status = self.server_status
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\__init__.py", line 215, in arg_wrapper
    _raise(t_e, _e)
  File "d:\programdata\anaconda3\envs\rasa1\lib\site-packages\bert_serving\client\_py3_var.py", line 9, in _raise
    raise t_e from _e
TimeoutError: no response from the server (with "timeout"=10000 ms), please check the following:is the server still online? is the network broken? are "port" and "port_out" correct? are you encoding a huge amount of data whereas the timeout is too small for that?

**Comment by GaoQ1** [comment]
额，你bert_as_server需要起个bert的服务的，不然这个component用不起来

**Comment by l2009312042** [comment]
@GaoQ1  多谢回复  如何启用bert这个服务呢？ 不熟悉还请指导一下

**Comment by GaoQ1** [comment]
我那个踩坑记里面有写

**Comment by l2009312042** [comment]
@GaoQ1  多谢 已经可以了

**Comment by l2009312042** [comment]
使用rasa X的时候 报如下的错误
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 373: invalid continuation byte

有什么建议没？谢谢
