### ISSUE TITLE
rasa train 时候出现了解码错误

### ISSUE THREAD

**Issue by BI4O** [GaoQ1/rasa_chatbot_cn#67]
Traceback (most recent call last):
  File "c:\anaconda3\envs\my_rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\my_rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\my_rasa\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\cli\train.py", line 84, in train
    kwargs=extract_additional_arguments(args),
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\train.py", line 40, in train
    kwargs=kwargs,
  File "c:\anaconda3\envs\my_rasa\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\train.py", line 72, in train_async
    domain = Domain.load(domain, skill_imports)
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\core\domain.py", line 78, in load
    other = cls.from_path(path, skill_imports)
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\core\domain.py", line 92, in from_path
    domain = cls.from_file(path)
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\core\domain.py", line 105, in from_file
    return cls.from_yaml(rasa.utils.io.read_file(path))
  File "c:\anaconda3\envs\my_rasa\lib\site-packages\rasa\utils\io.py", line 125, in read_file
    return f.read()
  File "c:\anaconda3\envs\my_rasa\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 373: invalid continuation byte

**Comment by felaray** [comment]
https://github.com/RasaHQ/rasa/issues/4116 這個問題官方知道 但等了很久就是不修

**Comment by GaoQ1** [comment]
这是什么问题？编码格式问题？

**Comment by BI4O** [comment]
问题已经得到了解决，解决办法就是keras==2.2.4, numpy==1.16.5放到requirements.txt中重新装一遍

**Comment by felaray** [comment]
原來如此! 感謝! 我以為要去看編碼問題..原來改版本就好了..
