### ISSUE TITLE
调用自定义组件失败

### ISSUE THREAD

**Issue by Dwyane3** [GaoQ1/rasa_chatbot_cn#71]
之前想调用一个第三方的闲聊机器人，但是失败；看了rasa文档后怀疑是第三方接口问题，于是把class ActionDefaultFallback(Action):改成class ActionDefaultFallback(Action):
    def name(self):
        return "action_default_fallback"

    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message('****************')
        #text = tracker.latest_message.get('text')
        #message = get_response(text)
        #if message['code'] == 100000:
            #dispatcher.utter_message("{}".format(message['text']))
        #else:
            #dispatcher.utter_template('utter_default', tracker)

        return [UserUtteranceReverted()]
还是报错：
Received user message '我傻了' with intent '{'name': 'unknown_intent', 'confidence': 0.4477413594722748}' and entities '[]'
2019-10-09 20:55:53 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 64 events
2019-10-09 20:55:53 DEBUG    rasa.core.policies.fallback  - NLU confidence 0.4477413594722748 is lower than NLU threshold 0.50. 
2019-10-09 20:55:53 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'prev_action_listen': 1.0, 'intent_unknown_intent': 1.0}, {'prev_action_default_fallback': 1.0, 'intent_unknown_intent': 1.0}, {'prev_action_listen': 1.0, 'intent_unknown_intent': 1.0}]
2019-10-09 20:55:53 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-10-09 20:55:53 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_FallbackPolicy
2019-10-09 20:55:53 DEBUG    rasa.core.processor  - Predicted next action 'action_default_fallback' with confidence 1.00.
2019-10-09 20:55:53 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_default_fallback'.
2019-10-09 20:55:55 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_default_fallback'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2019-10-09 20:55:55 DEBUG    rasa.core.processor  - Failed to execute custom action.
Traceback (most recent call last):
  File "/home/liuenli/anaconda3/lib/python3.6/site-packages/rasa/core/actions/action.py", line 399, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/home/liuenli/anaconda3/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/liuenli/anaconda3/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 148, in request
    resp.status, resp.reason, await resp.content.read()
rasa.utils.endpoints.ClientResponseError: 500, INTERNAL SERVER ERROR, body='b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>\n''

**Comment by Dwyane3** [comment]
望作者解答一下，谢谢
