### ISSUE TITLE
执行【rasa train --domain domain.yml --data data --config config.yml --out models】后 报错

### ISSUE THREAD

**Issue by shamrockzhao** [GaoQ1/rasa_chatbot_cn#72]
执行【rasa train --domain domain.yml --data data --config config.yml --out models】后 报错
错误信息如下：

Processed trackers:  99%|████████████████████████████████████████████▌| 466
Processed trackers: 100%|█████████████████████████████████████████████| 471
/471 [00:05<00:00, 81.08it/s, # actions=164]
Traceback (most recent call last):
  File "d:\softwares\envnlp\lib\site-packages\tensorflow\python\framework\ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension must be 5 but is 4 for 'attention_1/transpose_7' (op: 'Transpose') with input shapes: [?,16,?,16,?], [4].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python37\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python\Python37\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Softwares\envNLP\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "d:\softwares\envnlp\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "d:\softwares\envnlp\lib\site-packages\rasa\cli\train.py", line 75, in train
    kwargs=extract_additional_arguments(args),
  File "d:\softwares\envnlp\lib\site-packages\rasa\train.py", line 40, in train
    kwargs=kwargs,

**Comment by GaoQ1** [comment]
keras版本问题，参考[59](https://github.com/GaoQ1/rasa_chatbot_cn/issues/59)
