### ISSUE TITLE
关于rasa_nlu究极形态配置问题。

### ISSUE THREAD

**Issue by QinWinner** [GaoQ1/rasa_chatbot_cn#75]
我再用本项目的管道配置上是没有问题的。但是切换到究极形态的管道配置时候遇到问题不能解决。我只换了个配置。
2019-10-18 17:12:47 INFO     rasa.nlu.model  - Starting to train component KashgariIntentClassifier
2019-10-18 17:12:47 INFO     rasa.nlu.model  - Finished training component.
Traceback (most recent call last):
  File "/home/qinjian/.conda/envs/rasax/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/cli/train.py", line 137, in train_nlu
    fixed_model_name=args.fixed_model_name,
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/train.py", line 375, in train_nlu
    _train_nlu_async(config, nlu_data, output, train_path, fixed_model_name)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/train.py", line 403, in _train_nlu_async
    fixed_model_name=fixed_model_name,
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/train.py", line 427, in _train_nlu_with_validated_data
    config, file_importer, _train_path, fixed_model_name="nlu"
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/nlu/train.py", line 79, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "/home/qinjian/.conda/envs/rasax/lib/python3.7/site-packages/rasa/nlu/model.py", line 195, in train
    context.update(updates)
TypeError: 'coroutine' object is not iterable
sys:1: RuntimeWarning: coroutine 'KashgariIntentClassifier.train' was never awaited

**Comment by GaoQ1** [comment]
请再次查看文章

**Comment by QinWinner** [comment]
多谢大佬，最后的究极本readme我没看清。解决问题了。
