### ISSUE TITLE
make run-cmdline报错。RuntimeError: this event loop is already running.

### ISSUE THREAD

**Issue by YYGe01** [GaoQ1/rasa_chatbot_cn#83]
作者您好，运行make run-cmdline报错，不知道是什么原因。
2020-06-15 14:21:00 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/rasa/core/run.py:107> exception=RuntimeError('this event loop is already running.')>
Traceback (most recent call last):
  File "/Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/rasa/core/run.py", line 111, in run_cmdline_io
    server_url=constants.DEFAULT_SERVER_FORMAT.format(port)
  File "/Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/rasa/core/channels/console.py", line 122, in record_messages
    text = get_cmd_input(button_question)
  File "/Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/rasa/core/channels/console.py", line 71, in get_cmd_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "/Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/questionary/question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "/Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/questionary/question.py", line 59, in unsafe_ask
    return self.application.run()
  File "/Users/yyg/opt/anaconda3/envs/gao/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 480, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.

版本：
rasa:1.1.3
rasa-nlu-gao:1.0.3
tensorflow:1.13.2

谢谢！

**Comment by YYGe01** [comment]
这个地址已为我解决问题了。https://forum.rasa.com/t/error-this-event-loop-is-already-running/24017

另外，在安装过程中出现了很多版本冲突，我看issue上作者您提到rasa==1.1.3版本，估计是rasa-nlu-gao版本过高导致的。
ERROR: rasa 1.1.3 has requirement scikit-learn~=0.20.0, but you'll have scikit-learn 0.21.1 which is incompatible.
ERROR: rasa 1.1.3 has requirement scikit-learn~=0.20.2, but you'll have scikit-learn 0.21.1 which is incompatible.
ERROR: rasa 1.1.3 has requirement urllib3<1.25, but you'll have urllib3 1.25.7 which is incompatible.
ERROR: rasa-nlu-gao 1.0.3 has requirement tensorflow==1.14.0, but you'll have tensorflow 1.13.2 which is incompatible.

**Comment by GaoQ1** [comment]
只要安装rasa-nlu-gao就行了，会自动把对应依赖的rasa下载安装的。之前是有版本冲突问题。
