### ISSUE TITLE
rasa train出错

### ISSUE THREAD

**Issue by zengyazy** [GaoQ1/rasa_chatbot_cn#89]
rasa.core.policies.ensemble.InvalidPolicyConfig: Module for policy 'policy.attention_policy.AttentionPolicy' could not be loaded. Please make sure the name is a valid policy.在rasa train 时出现以上错误。
python3.7
win10
rasa                             1.1.3
rasa-core                        0.14.5
rasa-core-sdk                    0.14.0
rasa-nlu                         0.15.1
rasa-nlu-gao                     1.0.3
rasa-sdk                         1.1.1
Traceback (most recent call last):
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\registry.py", line 20, in policy_from_module_path
    return class_from_module_path(module_path, lookup_path="rasa.core.policies")
  File "f:\soft\envs\py37\lib\site-packages\rasa\utils\common.py", line 188, in class_from_module_path
    m = importlib.import_module(module_name)
  File "f:\soft\envs\py37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'policy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\policies\ensemble.py", line 279, in from_dict
    constr_func = registry.policy_from_module_path(policy_name)
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\registry.py", line 22, in policy_from_module_path
    raise ImportError("Cannot retrieve policy from path '{}'".format(module_path))
ImportError: Cannot retrieve policy from path 'policy.attention_policy.AttentionPolicy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:\soft\envs\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "f:\soft\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "F:\soft\envs\py37\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "f:\soft\envs\py37\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "f:\soft\envs\py37\lib\site-packages\rasa\cli\train.py", line 84, in train
    kwargs=extract_additional_arguments(args),
  File "f:\soft\envs\py37\lib\site-packages\rasa\train.py", line 40, in train
    kwargs=kwargs,
  File "f:\soft\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "f:\soft\envs\py37\lib\site-packages\rasa\train.py", line 135, in train_async
    kwargs=kwargs,
  File "f:\soft\envs\py37\lib\site-packages\rasa\train.py", line 174, in _do_training
    kwargs=kwargs,
  File "f:\soft\envs\py37\lib\site-packages\rasa\train.py", line 303, in _train_core_with_validated_data
    kwargs=kwargs,
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\train.py", line 36, in train
    policies = config.load(policy_config)
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\config.py", line 24, in load
    return PolicyEnsemble.from_dict(config_data)
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\policies\ensemble.py", line 287, in from_dict
    "".format(policy_name)
请问有人也出现这个问题的吗o(╥﹏╥)o刚学rasa的小白

**Comment by HYQQYH** [comment]
@zengyazy 请问你解决了吗这个问题，我也碰到了，还没找到解决方法

**Comment by GaoQ1** [comment]
试试export PYTHONPATH=/path/to/your/policy

**Comment by zengyazy** [comment]
> @zengyazy 请问你解决了吗这个问题，我也碰到了，还没找到解决方法

我现在没有跑这个项目了，但是刚刚作者在下面回答了，你可以试试   export PYTHONPATH=/path/to/your/policy

**Comment by zengyazy** [comment]
@HYQQYH  刚刚作者回答了这个问题，你可以试试 export PYTHONPATH=/path/to/your/policy
