### ISSUE TITLE
rasa shell bot load之后出错

### ISSUE THREAD

**Issue by zengyazy** [GaoQ1/rasa_chatbot_cn#90]
Bot loaded. Type a message and press enter (use '/stop' to exit):
2020-07-17 14:24:11 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at f:\soft\envs\py37\lib\site-packages\rasa\core\run.py:115> exception=RuntimeError('This event loop is already running')>
Traceback (most recent call last):
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\run.py", line 119, in run_cmdline_io
    server_url=constants.DEFAULT_SERVER_FORMAT.format(port)
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\channels\console.py", line 128, in record_messages
    text = get_cmd_input(button_question)
  File "f:\soft\envs\py37\lib\site-packages\rasa\core\channels\console.py", line 75, in get_cmd_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "f:\soft\envs\py37\lib\site-packages\questionary\question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "f:\soft\envs\py37\lib\site-packages\questionary\question.py", line 59, in unsafe_ask
    return self.application.run()
  File "f:\soft\envs\py37\lib\site-packages\prompt_toolkit\application\application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "f:\soft\envs\py37\lib\asyncio\base_events.py", line 563, in run_until_complete
    self._check_runnung()
  File "f:\soft\envs\py37\lib\asyncio\base_events.py", line 523, in _check_runnung
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
f:\soft\envs\py37\lib\asyncio\base_events.py:1771: RuntimeWarning: coroutine 'Application.run_async' was never awaited
  handle = self._ready.popleft()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
请问有仁兄遇到或解决了以上问题的吗，请指点一下

**Comment by littlestar502** [comment]
请问解决了吗

**Comment by GaoQ1** [comment]
依赖版本对吗？
