### ISSUE TITLE
docker也运行不起来

### ISSUE THREAD

**Issue by wewillydy** [GaoQ1/rasa_chatbot_cn#92]
执行 sh dev/deploy_dev.sh 后仍不能用，使用docker logs -f chatbot_dev查看，发现下面这个错误：

2020-10-13 08:22:04 INFO     root  - Starting Rasa server on http://localhost:5005
2020-10-13 08:22:04 INFO     root  - Enabling coroutine debugging. Loop id 94466493218488.
2020-10-13 08:22:05 DEBUG    rasa.model  - Extracted model to '/tmp/tmp5z_50p0s'.
2020-10-13 08:22:05 DEBUG    root  - Could not load interpreter from 'models'.
2020-10-13 08:22:05 DEBUG    rasa.core.tracker_store  - Connected to MongoTrackerStore.
2020-10-13 08:22:05 DEBUG    rasa.model  - Extracted model to '/tmp/tmpmfiber9a'.
2020-10-13 08:22:05 ERROR    rasa.core.agent  - Could not load model due to Failed to find component class for 'components.extractors.jieba_pseg_extractor.JiebaPsegExtractor'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module..
[2020-10-13 08:22:05 +0000] [302] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 141, in get_component_class
    return class_from_module_path(component_name)
  File "/usr/local/lib/python3.6/site-packages/rasa/utils/common.py", line 174, in class_from_module_path
    m = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'components.extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 218, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 264, in load_agent
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 924, in load_local_model
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 373, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 323, in create
    components.validate_requirements(model_metadata.component_classes)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/components.py", line 36, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 150, in get_component_class
    "in a module.".format(component_name)
Exception: Failed to find component class for 'components.extractors.jieba_pseg_extractor.JiebaPsegExtractor'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 141, in get_component_class
    return class_from_module_path(component_name)
  File "/usr/local/lib/python3.6/site-packages/rasa/utils/common.py", line 174, in class_from_module_path
    m = importlib.import_module(module_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'components.extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 88, in run
    rasa.run(**vars(args))
  File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 55, in run
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 179, in serve_application
    app.run(host="0.0.0.0", port=port)
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 218, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 264, in load_agent
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 924, in load_local_model
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 373, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 323, in create
    components.validate_requirements(model_metadata.component_classes)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/components.py", line 36, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 150, in get_component_class
    "in a module.".format(component_name)
Exception: Failed to find component class for 'components.extractors.jieba_pseg_extractor.JiebaPsegExtractor'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
make: *** [Makefile:9: run] Error 1

**Comment by GaoQ1** [comment]
建议使用新版本
