### ISSUE TITLE
ModuleNotFoundError: No module named 'rasa_core_sdk'

### ISSUE THREAD

**Issue by 812406210** [GaoQ1/rasa_chatbot_cn#95]
Error  Info  > 
2021-03-02 15:28:58 ERROR    rasa_sdk.executor  - Failed to register package 'actions'.
Traceback (most recent call last):
  File "/root/.virtualenvs/chat/lib/python3.7/site-packages/rasa_sdk/executor.py", line 250, in register_package
    self._import_submodules(package)
  File "/root/.virtualenvs/chat/lib/python3.7/site-packages/rasa_sdk/executor.py", line 213, in _import_submodules
    self._import_module(full_name)
  File "/root/.virtualenvs/chat/lib/python3.7/site-packages/rasa_sdk/executor.py", line 227, in _import_module
    module = importlib.import_module(name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/rasa_chatbot_cn-master/actions/actions.py", line 6, in <module>
    from rasa_core_sdk import Action
ModuleNotFoundError: No module named 'rasa_core_sdk'
Makefile:8: recipe for target 'run-actions' failed
make[1]: *** [run-actions] Error 1
make[1]: Leaving directory '/root/rasa_chatbot_cn-master'

你好，请问这个也版本的问题吗？谢谢

**Comment by GaoQ1** [comment]
你是怎么执行的？

**Comment by 812406210** [comment]
make run-actions，按照Makefile文件中的执行的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Colin"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午4:05
收件人: "GaoQ1/rasa_chatbot_cn"<rasa_chatbot_cn@noreply.github.com&gt;; 
抄送: "想你"<812406210@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GaoQ1/rasa_chatbot_cn] ModuleNotFoundError: No module named &#39;rasa_core_sdk&#39; (#95)





 
你是怎么执行的？

**Comment by 812406210** [comment]
我这边训练没有报错，就是执行测试的时候有这个错误，请问是怎么回事呀？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GaoQ1/rasa_chatbot_cn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 下午4:05
收件人:&nbsp;"GaoQ1/rasa_chatbot_cn"<rasa_chatbot_cn@noreply.github.com&gt;;
抄送:&nbsp;"想你"<812406210@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GaoQ1/rasa_chatbot_cn] ModuleNotFoundError: No module named 'rasa_core_sdk' (#95)





 
你是怎么执行的？

**Comment by GaoQ1** [comment]
rasa==1.10.18
rasa-sdk==1.10.3
transformers==2.4.1
是这几个版本？

**Comment by 812406210** [comment]
是的，版本是对的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Colin"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午5:39
收件人: "GaoQ1/rasa_chatbot_cn"<rasa_chatbot_cn@noreply.github.com&gt;; 
抄送: "想你"<812406210@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GaoQ1/rasa_chatbot_cn] ModuleNotFoundError: No module named &#39;rasa_core_sdk&#39; (#95)





 
rasa==1.10.18
 rasa-sdk==1.10.3
 transformers==2.4.1
 是这几个版本？

**Comment by 812406210** [comment]
还有根据你的博客，我修改config.yml，同时在data目录下加入otal_word_feature_extractor_zh.dat这个数据集，然后执行make train，即可训练模型，是吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Colin"<notifications@github.com&gt;; 
发送时间: 2021年3月2日(星期二) 下午5:39
收件人: "GaoQ1/rasa_chatbot_cn"<rasa_chatbot_cn@noreply.github.com&gt;; 
抄送: "想你"<812406210@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [GaoQ1/rasa_chatbot_cn] ModuleNotFoundError: No module named &#39;rasa_core_sdk&#39; (#95)





 
rasa==1.10.18
 rasa-sdk==1.10.3
 transformers==2.4.1
 是这几个版本？

**Comment by GaoQ1** [comment]
data下面数据集应该是rasa支持的格式，rasa1版本是md格式，rasa2支持的是yaml格式

**Comment by hua7448** [comment]
> Error Info >
> 2021-03-02 15:28:58 ERROR rasa_sdk.executor - Failed to register package 'actions'.
> Traceback (most recent call last):
> File "/root/.virtualenvs/chat/lib/python3.7/site-packages/rasa_sdk/executor.py", line 250, in register_package
> self._import_submodules(package)
> File "/root/.virtualenvs/chat/lib/python3.7/site-packages/rasa_sdk/executor.py", line 213, in _import_submodules
> self._import_module(full_name)
> File "/root/.virtualenvs/chat/lib/python3.7/site-packages/rasa_sdk/executor.py", line 227, in _import_module
> module = importlib.import_module(name)
> File "/usr/lib/python3.7/importlib/**init**.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "", line 1006, in _gcd_import
> File "", line 983, in _find_and_load
> File "", line 967, in _find_and_load_unlocked
> File "", line 677, in _load_unlocked
> File "", line 728, in exec_module
> File "", line 219, in _call_with_frames_removed
> File "/root/rasa_chatbot_cn-master/actions/actions.py", line 6, in
> from rasa_core_sdk import Action
> ModuleNotFoundError: No module named 'rasa_core_sdk'
> Makefile:8: recipe for target 'run-actions' failed
> make[1]: *** [run-actions] Error 1
> make[1]: Leaving directory '/root/rasa_chatbot_cn-master'
> 
> 你好，请问这个也版本的问题吗？谢谢

把rasa_core_sdk改为rasa_sdk即可
